### ISSUE TITLE
Exporting or saving plots to pdf file

### ISSUE THREAD

**Issue by francat** [scverse/muon#49]
Hi there! 

I wanted to thank you for this fantastic tool and beautiful tutorials. It has saved me SO much time and headache.

I wondered if there is a way to export the plots I make with muon to pdf, tiff, or png files? I apologize if this was already covered and I missed it; I don't see a 'save' parameter like the one in Scanpy, nor can I use plt.savefig() function as one can with seaborn plots. 

I apologize for this trivial question/request, but I hoped to export said pdfs into illustrator to edit the axis labels. 

Thank you for your time!

Cheers,
Fran

**Comment by gtca** [comment]
Hey @francat!

First of all, thank you for your kind feedback, I'm glad to hear you find `muon` useful!

As we build `muon` plotting relying on `scanpy`, the same things should work. Plotting functions explicitly list only some necessary arguments here, for some internal processing, and the rest is expected to be provided to scanpy directly for plotting. The benefit of this is that whenever some of these are changed in `scanpy`, `muon` plotting can just continue to work, in most cases. 
The downside of that is that all these options are only listed in the docstring for the respective`scnapy` function but we try to point to them, e.g. in the `mu.pl.embedding` docsting there's a statement pointing to `sc.pl.embedding`. 
It is a good point that this needs to be better documented so I've opened #50 to track it.

So `save=...` argument should work in plotting functions — otherwise please file a bug report!

**Comment by gtca** [comment]
By the way, for the `plt.savefig()` to work, I believe providing `show=False` to `mu.pl.*`, which is also expected to work, should be enough.

**Comment by ivirshup** [comment]
Over at scanpy, [we'd love to have a better way to do this](https://github.com/theislab/scanpy/issues/1508#issuecomment-735050380). Would probably make sense to solve this together?

**Comment by gtca** [comment]
Thanks for chiming in, @ivirshup!

Indeed, and [the common plotting library discussion](https://github.com/theislab/scanpy/issues/1832) would also be relevant in that regard. E.g. if we can have a more low-level `scplot` library with modules re-usable by `scanpy`, `muon`, `scirpy`, etc., that might improve the state of things in the ecosystem.
In the foreseeable future, it will probably still make sense for `muon` to use `scanpy` plotting function calls.
