### ISSUE TITLE
Bugs in muon.pp.neighbors(mdata, key_added='wnn')

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/muon#89]
Hi, when I tried WNN by muon, I received this bug:
![image](https://user-images.githubusercontent.com/43333475/215012008-83bd8d8e-637f-4f96-bb33-59d07cdf3846.png)
Are there any solutions to this bug? Thanks.

**Comment by gtca** [comment]
Hey @HelloWorldLTY,

Were the neighbour graphs for individual modalities recomputed appropriately before running WNN?

If so, could you please provide more details to reproduce this?

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your explaniation. Yes, I find out the reason is exactly what you mentioned. 
However, I still have another question related to wnn method. I wonder if it is possible to plot the entire joint embedding of atac seq and rna seq data like:
https://satijalab.org/seurat/articles/atacseq_integration_vignette.html
It seems that muon's wnn method will adjust the cell number of atacseq and rna seq data. Thanks.

**Comment by gtca** [comment]
Hey,

Sure, you can use the WNN graph as input to `mu.tl.umap` as demonstrated [in this tutorial](https://muon-tutorials.readthedocs.io/en/latest/cite-seq/2-CITE-seq-PBMC-5k-Weighted-Neighbours.html)!

Just to note, the co-embedding in the tutorial you linked seems to be performed using imputation and is only for demonstration purposes as mentioned there. I'm not sure there's a one-liner analogue I can propose here.
Please feel free to give more feedback on this if you find this useful and practical for some application given that there's a way to embed data directly (vs imputation-guided approach).

Alternative way to produce a joint embedding would be to impute gene activity scores and align it with the RNA part of the dataset.

Please note that in the multiome data both modalities are profiled in the same cell. In the last two approaches this value of multiome is not utilised — and they can be applied to disjoint scRNA-seq and scATAC-seq datasets.

**Comment by HelloWorldLTY** [comment]
Hi, I think the current WNN method automically select same number of cells for both atac and rna data. Is my understanding correct? I wonedr if the WNN method can use all of the cells I have as input without bugs. Thanks.

**Comment by gtca** [comment]
Hey, I'm not sure I follow the question about the cell numbers but I'll try to elaborate. WNN is a method for _vertical integration_, i.e. cells are _the same_ for this integration task. E.g. see [this perspective](nature.com/articles/s41587-021-00895-7) on integration tasks and challenges.

For instance, as I understand, Seurat implementation of WNN requires cells to be exactly the same across modalities, which is also ensured by the constraints of that data object.

I am not familiar with the WNN-based approach extended to handle missing samples in individual modalities at the moment. Feel free to share if you have any pointers and ideas!
A naïve approach to handle this now could be imputing missing data per modality from local cell neighbours in order to be able to use all the cells for training.
For multiome data however, all the cells should be available in the original data, so it seems an appropriate filtering approach will already enable you to embed all the cells relying on WNN.

It is also possible to generate a MOFA-based embedding when the cells are missing in some modalities as the method has been designed to handle missing samples (cells).

**Comment by HelloWorldLTY** [comment]
Ok, thanks a lot!
